class PlayerResponse:
    def __init__(self, response):
        position = response.get('currentPosition', {})
        self.current_position = (position.get('row'), position.get('col'))
        self.id = response.get('id')
        self.spawn_begin = response.get('spawnBegin')
        self.power = response.get('power')
        self.speed = response.get('speed')
        self.delay = response.get('delay')
        self.score = response.get('score')
        self.lives = response.get('lives')
        self.box = response.get('box')
        self.sticky_rice = response.get('stickyRice')
        self.chung_cake = response.get('chungCake')
        self.nine_tusk_elephant = response.get('nineTuskElephant')
        self.nine_spur_rooster = response.get('nineSpurRooster')
        self.nine_mane_hair_horse = response.get('nineManeHairHorse')
        self.holy_spirit_stone = response.get('holySpiritStone')
        self.eternal_badge = response.get('eternalBadge')
        self.brick_wall = response.get('brickWall')
        self.transform_type = response.get('transformType')
        self.has_transform = response.get('hasTransform')
        self.owner_weapon = response.get('ownerWeapon')
        self.cur_weapon = response.get('currentWeapon')
        self.is_stun = response.get('isStun')
        self.is_child = response.get('isChild')
        self.time_to_use_special_weapons = response.get('timeToUseSpecialWeapons')
